BEGIN;
CREATE TABLE IF NOT EXISTS Blacklists (id BIGINT NOT NULL, type TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Prefixes (guild BIGINT NOT NULL, prefix TEXT NOT NULL, PRIMARY KEY(guild, prefix));
CREATE TABLE IF NOT EXISTS ErrorLogs (
    id BIGINT PRIMARY KEY,
    command TEXT NOT NULL,
    error TEXT NOT NULL,
    full_error TEXT NOT NULL,
    message TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Features (id BIGINT NOT NULL, type TEXT NOT NULL);
COMMIT;