CREATE TABLE IF NOT EXISTS Blacklists (id INTEGER NOT NULL, type TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS Prefixes (guild INTEGER NOT NULL, prefix TEXT NOT NULL, PRIMARY KEY(guild, prefix)) STRICT;
CREATE TABLE IF NOT EXISTS ErrorLogs (
    id INTEGER PRIMARY KEY,
    command TEXT NOT NULL,
    error TEXT NOT NULL,
    full_error TEXT NOT NULL,
    message TEXT NOT NULL
) STRICT;
CREATE TABLE IF NOT EXISTS Features (id INTEGER NOT NULL, type TEXT NOT NULL) STRICT;
